### ISSUE TITLE
Issue on about-events-backgroundImage

### ISSUE THREAD

**Issue by JahowChen** [TEDxMaplelLeaf/TEDxMapleLeaf#1]
The background image does not change after replacing image url in data.js .
Guess the problem is here:
Line 164: `aboutEventCont.style.backgroundImage = 'url("static/imgs/about-event-ph.svg")';`

**Comment by shifuchen** [comment]
You're right. I set it static for testing. Some corrections are just made so that the data in data.js could be reflected.
